# Generated by Django 4.2.5 on 2023-10-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_table',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='form_table',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
